-- 중고제품 테이블
CREATE TABLE used_product (
  used_seq bigint generated by default as identity primary key,
  title varchar(100) not null,
  category_code varchar(30) references common_code(cc_code),
  content text,
  status varchar(10) default 'SALE', -- 'SALE', 'SOLD'
  view_cnt bigint default 0,
  thumbnail_url varchar(500),
  reg_id varchar(30),
  mod_id varchar(30),
  reg_date timestamptz default now(),
  mod_date timestamptz default now()
);

-- 중고제품 사진 테이블
CREATE TABLE used_product_image (
  img_seq bigint generated by default as identity primary key,
  used_seq bigint references used_product(used_seq) on delete cascade,
  image_url varchar(500) not null,
  is_thumbnail boolean default false,
  sort_order smallint default 0,
  reg_date timestamptz default now()
);

-- RLS 비활성화 (테스트 환경용)
ALTER TABLE used_product DISABLE ROW LEVEL SECURITY;
ALTER TABLE used_product_image DISABLE ROW LEVEL SECURITY;
